[package]
# Semantic Versioning is used: https://semver.org/
version = "2.0.0"

# The title and description fields are primarily for displaying extension info in UI
title = "Edge Impulse Data Ingestion - Ashvin"
description="Edge Impulse Data Ingestion extension for Omniverse."

# Path (relative to the root) or content of readme markdown file for UI.
readme  = "docs/README.md"

# URL of the extension source repository.
repository = ""

# One of categories for UI.
category = "Example"

# Keywords for the extension
keywords = ["kit", "example"]

# Icon to show in the extension manager
icon = "data/icon.png"

# Preview to show in the extension manager
preview_image = "data/preview.png"

# Use omni.ui to build simple UI
[dependencies]
"omni.kit.uiapp" = {}

# Main python module this extension provides, it will be publicly available as "import omni.example.apiconnect".
[[python.module]]
name = "edgeimpulse.dataingestion"

[[test]]
# Extra dependencies only to be used during test run
dependencies = [
    "omni.kit.ui_test" # UI testing extension
]

[python.pipapi]
requirements = [
    "httpx==0.21.1",
    "pyyaml",
    "webbrowser"
]
use_online_index = true